### ISSUE TITLE
Better Slack notifications

### ISSUE THREAD

**Issue by nicolaei** [nsbno/terraform-aws-continuous-delivery#2]
An idea would be to make the slack notifications even better than today using the slack block API.
We do have a solution today, using [the existing slack integration that was created two years ago, but it's a bit lackluster.](https://github.com/nsbno/terraform-stepfunction-status-slack)

## Suggested Idea

Make a new slackbot that is configured using the YAML file like this:

```yaml
notify:
  # Post to this channel
  channel: pipeline-notifications
  # Only notify on these statuses
  status: [FAILURE, SUCCESS, STARTED]
```

Together with the slack block API we could enrich the message to link directly to the log-output.
