### ISSUE TITLE
Pull Request Previews

### ISSUE THREAD

**Issue by nicolaei** [nsbno/terraform-aws-continuous-delivery#5]
Adding pull request previews can make reviews easier by allowing teams to see the results.

## Suggested Idea

For example terraform previews could be the terraform plan, and frontend previews can be deploys ala netlify.

Use GitHub deploys (so link this with #5) for a native experience.

```yaml
# Generate terraform plan in your pull request
pull_requests:
  deployment_preview:
    type: terraform

# Get a link to an ephemeral frontend deployment
pull_requests:
  deployment_preview:
    type: frontend
```

For the terraform previews, it could also be possible to use workspaces.
Some inspiration: https://hackernoon.com/from-feature-branches-to-feature-environments-with-terraform-10973ycb
